{{- if .Values.ingress.enabled }}
{{- range .Values.ingress.hosts }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{- printf "%s-%s" .name $.Release.Name | trunc 63 | trimSuffix "-" -}}"
  labels:
    app: {{ template "stellar-horizon.name" $ }}
    chart: {{ template "stellar-horizon.chart" $ }}
    release: {{ $.Release.Name }}
    heritage: {{ $.Release.Service }}
  annotations:
    {{- range $key, $value := .annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
  - host: {{ .name }}
    http:
      paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: {{ template "stellar-horizon.fullname" $ }}
            servicePort: http
{{- if .tls }}
  tls:
  - hosts:
    - {{ .name }}
    {{- with .tlsSecret }}
    secretName: {{ .tlsSecret }}
    {{- end }}
{{- end }}
---
{{- end }}
{{- end }}
