{{- if .Values.existingDatabase.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "stellar-horizon.fullname" . }}
  labels:
    app: {{ template "stellar-horizon.name" . }}
    chart: {{ template "stellar-horizon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  databasePassword: {{ .Values.existingDatabase.password | b64enc }}
{{- end }}
