apiVersion: v1
kind: Service
metadata:
  name: {{ template "stellar-horizon.fullname" . }}
  labels:
    app: {{ template "stellar-horizon.name" . }}
    chart: {{ template "stellar-horizon.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "stellar-horizon.name" . }}
    release: {{ .Release.Name }}
