dependencies:
- name: postgresql
  version: ^5.0.0
  repository: "https://charts.helm.sh/stable/"
  condition: postgresql.enabled
- name: stellar-core
  version: ^1.0.0
  repository: "file://../stellar-core/"
  condition: stellar-core.enabled
